# MAIN base
baseURL = "http://deepdivesweb.s3-website.eu-west-2.amazonaws.com/"
languageCode = "en-us"
title = "Deep Dives | Cloud training with a difference."
theme = "apsho"

# URL Params
[permalinks]
uglyUrl = false

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "http://deepdivesweb.s3-website.eu-west-2.amazonaws.com/#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "http://deepdivesweb.s3-website.eu-west-2.amazonaws.com/#feature"
    weight = 2
[[menu.main]]
    name = "Courses"
    url = "/courses"
    weight = 3
[[menu.main]]
    name = "Team"
    url = "http://deepdivesweb.s3-website.eu-west-2.amazonaws.com/#team"
    weight = 4
[[menu.main]]
    name = "FAQ"
    url = "http://deepdivesweb.s3-website.eu-west-2.amazonaws.com/#faq"
    weight = 5
[[menu.main]]
    name = "Blog"
    url = "https://blog.deepdives.eu/"
    weight = 10
    [menu.main.params]
    external = true

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "http://deepdivesweb.s3-website.eu-west-2.amazonaws.com/"
    weight = 1
[[menu.sitemap]]
    name = "Courses"
    url = "/courses"
    weight = 2
[[menu.sitemap]]
    name = "Blog"
    url = "https://blog.deepdives.eu/"
    weight = 2
    [menu.sitemap.params]
    external = true
[[menu.sitemap]]
    name = "Privacy Policy"
    url = "http://deepdivesweb.s3-website.eu-west-2.amazonaws.com/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    url = "http://deepdivesweb.s3-website.eu-west-2.amazonaws.com/contact"
    weight = 4

# Footer Address
[params.address]
address = "Deep Dives Oy, PO Box 333, 00121 Helsinki, Finland"
email = "info@deepdives.eu"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/#"
instagram = "https://instagram.com/#"

[params]

# Header
logo = "images/logo.png"
formspreeURL = "https://formspree.io/f/mzbwkwzy"
googleAnalytics = "#"

# Footer
footerTitle = "Subscribe And Stay Updated"
copyright1 = "All Rights Reserved"
copyright2 = "Copyright Â© Deep Dives {year}"

#contact
email = "info@deepdives.eu"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "deepdiveswebdev"
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
# URL = "s3://deepdivesweb?region=eu-west-2"